// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Directa, no pooled: `prisma migrate` toma un advisory lock que necesita
    // sesión persistente, y el pooler de Neon (PgBouncer modo transacción) no
    // la garantiza entre statements. La app en runtime usa DATABASE_URL
    // (pooled) vía src/lib/prisma.ts, no esta config.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
