/**
 * Íconos que se pueden elegir para las tarjetas de un sitio. Lista cerrada: el
 * valor guardado es solo un nombre de esta lista (el renderizador lo traduce a
 * un componente de lucide-react), nunca un SVG ni una URL.
 */
export const SITE_ICONS = [
  'check',
  'star',
  'heart',
  'shield',
  'truck',
  'clock',
  'phone',
  'mail',
  'map-pin',
  'zap',
  'award',
  'users',
  'smile',
  'thumbs-up',
  'leaf',
  'sun',
  'wrench',
  'hammer',
  'scissors',
  'camera',
  'music',
  'coffee',
  'shopping-bag',
  'credit-card',
  'gift',
  'sparkles',
  'rocket',
  'target',
  'trending-up',
  'home',
  'car',
  'briefcase',
  'graduation-cap',
  'stethoscope',
  'utensils',
  'palette',
  'code',
  'globe',
  'calendar',
  'lock',
] as const;

export type SiteIcon = (typeof SITE_ICONS)[number];

export const SITE_ICON_LABELS: Record<SiteIcon, string> = {
  check: 'Visto bueno',
  star: 'Estrella',
  heart: 'Corazón',
  shield: 'Escudo (seguridad)',
  truck: 'Camión (despacho)',
  clock: 'Reloj',
  phone: 'Teléfono',
  mail: 'Correo',
  'map-pin': 'Ubicación',
  zap: 'Rayo (rapidez)',
  award: 'Medalla',
  users: 'Personas',
  smile: 'Sonrisa',
  'thumbs-up': 'Pulgar arriba',
  leaf: 'Hoja (natural)',
  sun: 'Sol',
  wrench: 'Llave (reparación)',
  hammer: 'Martillo',
  scissors: 'Tijeras',
  camera: 'Cámara',
  music: 'Música',
  coffee: 'Café',
  'shopping-bag': 'Bolsa de compras',
  'credit-card': 'Tarjeta de pago',
  gift: 'Regalo',
  sparkles: 'Destellos',
  rocket: 'Cohete',
  target: 'Objetivo',
  'trending-up': 'Crecimiento',
  home: 'Casa',
  car: 'Auto',
  briefcase: 'Maletín',
  'graduation-cap': 'Birrete (educación)',
  stethoscope: 'Estetoscopio (salud)',
  utensils: 'Cubiertos (comida)',
  palette: 'Paleta (diseño)',
  code: 'Código',
  globe: 'Mundo',
  calendar: 'Calendario',
  lock: 'Candado',
};
