import {
  Award,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  Clock,
  Code,
  Coffee,
  CreditCard,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  House,
  Leaf,
  Lock,
  Mail,
  MapPin,
  Music,
  Palette,
  Phone,
  Rocket,
  Scissors,
  Shield,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Target,
  ThumbsUp,
  TrendingUp,
  Truck,
  Users,
  Utensils,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { SiteIcon } from '@/lib/web-sites/icons';

/**
 * Nombre de ícono de una tarjeta (`SITE_ICONS`) → componente de lucide-react,
 * para que el editor muestre el ícono elegido. `Record` obliga a que cada
 * nombre de la lista cerrada tenga su componente. Los importa por nombre para
 * que el empaquetado deje fuera los que no se usan.
 */
export const SITE_ICON_COMPONENTS: Record<SiteIcon, LucideIcon> = {
  check: Check,
  star: Star,
  heart: Heart,
  shield: Shield,
  truck: Truck,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  'map-pin': MapPin,
  zap: Zap,
  award: Award,
  users: Users,
  smile: Smile,
  'thumbs-up': ThumbsUp,
  leaf: Leaf,
  sun: Sun,
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  camera: Camera,
  music: Music,
  coffee: Coffee,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  gift: Gift,
  sparkles: Sparkles,
  rocket: Rocket,
  target: Target,
  'trending-up': TrendingUp,
  home: House,
  car: Car,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  stethoscope: Stethoscope,
  utensils: Utensils,
  palette: Palette,
  code: Code,
  globe: Globe,
  calendar: Calendar,
  lock: Lock,
};
